# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BeRLYzR8D-b8mGkow8Xsw_Q0SHpwGn1k
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2,2,100)

y1 = np.sqrt((1-(np.abs(x)-1)**2))
y2 = np.arccos(1-np.abs(x)) - np.pi

plt.plot(x,y1,'r')
plt.plot(x,y2,'r')
plt.show()